# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('wx_id', models.CharField(blank=True, max_length=100)),
                ('long', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=700)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('\u5f85\u89e3\u51b3', '\u5f85\u89e3\u51b3'), ('\u89e3\u51b3\u4e2d', '\u89e3\u51b3\u4e2d'), ('\u5df2\u5b8c\u6210', '\u5df2\u5b8c\u6210')], default=('\u5f85\u89e3\u51b3', '\u5f85\u89e3\u51b3'), max_length=10)),
                ('long', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('mp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish.MPUser')),
            ],
        ),
    ]
