# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpuser',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mpuser',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wish',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wish',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
